import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import StoreProvider from '@/app/StoreProvider';
import { Container, ThemeProvider } from '@mui/system';
import { CssBaseline } from '@mui/material';
import theme from '@/app/theme';
import Navbar from '@/components/ui/Navbar/Navbar';
import { getSession } from '@/lib/actions/getSession';
import { connectToDb } from '@/lib/db';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
	const session = JSON.stringify(await getSession());
	await connectToDb();
	return (
		<ThemeProvider theme={theme}>
			<CssBaseline />
			<StoreProvider>
				<html lang="en" style={{ height: '100%' }}>
					<body className={inter.className} style={{ margin: '0', height: '100%' }}>
						<header>
							<Navbar sessionString={session} />
						</header>
						<Container style={{ height: '100%' }}>{children}</Container>
					</body>
				</html>
			</StoreProvider>
		</ThemeProvider>
	);
};

export default RootLayout;
