import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { Provider } from 'react-redux';
import storeProvider from '@/app/StoreProvider';
import StoreProvider from '@/app/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
	<StoreProvider>
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	</StoreProvider>
);
export default RootLayout;
