import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import StoreProvider from '@/app/StoreProvider';
import { Container, ThemeProvider } from '@mui/system';
import { CssBaseline } from '@mui/material';
import theme from '@/app/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
	<ThemeProvider theme={theme}>
		<CssBaseline />
		<StoreProvider>
			<html lang="en" style={{ height: '100%' }}>
				<body className={inter.className} style={{ margin: '0', height: '100%' }}>
					<Container style={{ border: '2px solid green', height: '100%' }}>{children}</Container>
				</body>
			</html>
		</StoreProvider>
	</ThemeProvider>
);
export default RootLayout;
